AWSTemplateFormatVersion: '2010-09-09'
Description: Infrastructure Stack (S3, SQS, EventBridge, IAM)

Parameters:
  MyVisibilityTimeout:
    Type: Number
    Default: 60

Resources:
  # --- S3 ---
  MySourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-learning-bucket-12345
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  # --- DLQ ---
  MyDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: my-learning-dlq

  # --- Main SQS ---
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: my-learning-queue
      VisibilityTimeout: !Ref MyVisibilityTimeout
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MyDLQ.Arn
        maxReceiveCount: 3

  MyQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MyQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt MyQueue.Arn

  # --- EventBridge ---
  MyEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: default
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
              - !Ref MySourceBucket
      Targets:
        - Arn: !GetAtt MyQueue.Arn
          Id: MyQueueTarget

  # --- IAM Role ---
  MyFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole

# ------------------------------------------------------------
# Outputs
# ------------------------------------------------------------
Outputs:

  ExportedQueueArn:
    Value: !GetAtt MyQueue.Arn
    Export:
      Name: MyQueueArn-Export

  ExportedRoleArn:
    Value: !GetAtt MyFunctionRole.Arn
    Export:
      Name: MyFunctionRoleArn-Export